services:
  postgres:
    image: postgres:15
    container_name: wallet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7
    container_name: wallet-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

#  wallet-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: wallet-app
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env.docker  # optional, remove this line if you don't use it
#    restart: unless-stopped
#    environment:
#      - GO_ENV=docker
#    depends_on:
#      - redis
#      - postgres

volumes:
  pgdata:
  redisdata:
